---
title: "fLUE~MODIS (LSOCV)"
author: "Yousra El-Mejjaouy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fLUE~Landsat (LSOCV)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Prediction of fLUE using MODIS Bands 

## Variable importance 

Same applied to MODIS data  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(vip)
library(patchwork)
library(dplyr)
library(here)
library(readr)

```


print(p1)
```{r echo = FALSE, message=FALSE, warning=FALSE}
#| code-fold: true
#| label: Variable importance
#| fig-cap: "Variable importance for the regression model with MODIS data alone (a) and meteo data included (b)  "
#| fig-align: "center"
#| out-width: "100%"
#| fig-width: 10
#| fig-height: 5

# Read in precompiled models
regression_model<- readRDS(here::here("data/model_rf.rds"))

regression_model$finalModel$xNames


pred_colors <- c(
  "nd_NR_B1_NR_B4" = "#66796B",
  "LST"   = "#D8B08C",
  "pcwd_era5" = "#BA8E7A",
  "nd_NR_B1_NR_B2" = "#EFDFCC",
  "NR_B7" = "#D7A184",
  "nd_NR_B2_NR_B7" = "#D4C2AD",
  "nd_NR_B2_NR_B6" = "#86A69D",
  "nd_NR_B2_NR_B5" = "#F2B263",
   "t2m_era5"= "#008F8C",
  "NR_B1"= "#015958"
)

preds <- regression_model$pred
preds$site <- df$site[preds$rowIndex]

preds <- preds %>%
  rename(
    fLUE = obs,
    fLUE_predicted = pred
  )

out <- rgeco::analyse_modobs2(
  preds,
  mod = "fLUE_predicted",
  obs = "fLUE",
  type = "hex",
  pal = "magma",
  shortsubtitle = TRUE
)

out$gg

#the model with MODIS bands 
p1 <- vip(regression_model, geom = "col", aesthetics = list(fill = pred_colors, width = 0.7)) +
  labs(#title = "Landsat VIP", 
       y = "Variable importance") +
 # ylim(0, 0.6) +
  theme_classic() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
       panel.grid.major = element_blank(),  # Removes major grid lines
    panel.grid.minor = element_blank(),
    axis.text = element_text(size = 10)
  )
print(p1)


# Print the combined plot
combined1 <- p1 + p2 + 
  plot_layout(ncol = 2) + 
  plot_annotation(
    tag_levels = "a",
    tag_prefix = "(",
    tag_suffix = ")"
    )

print(combined1)

ggsave("fig/VIP.png", width = 7, height = 5, dpi =700)
```


```{r echo = FALSE, message=FALSE, warning=FALSE}
##the regression model with MODIS data 
set.seed(0)

# read in training data
#readRDS to have the cluster variable for plotting clusters 
#na.omit to have same dataset on which the model was built 

ml_df <- readRDS(
  here::here("data/machine_learning_training_data_meteo.rds")
) |> 
 select (-date, -doy, -year, -VPD_DAY_F_MDS,-TA_DAY_F_MDS) |>
  rename(
    NR_B1 = Nadir_Reflectance_Band1,
    NR_B2 = Nadir_Reflectance_Band2,
    NR_B3 = Nadir_Reflectance_Band3,
    NR_B4 = Nadir_Reflectance_Band4,
    NR_B5 = Nadir_Reflectance_Band5,
    NR_B6 = Nadir_Reflectance_Band6,
    NR_B7 = Nadir_Reflectance_Band7, 
    LST = LST_Day_1km) |>
   na.omit()

# create a data split across
# across both droughted and non-droughted days
ml_df_split <- ml_df |>
  rsample::initial_split(
    strata = is_flue_drought,
    prop = 0.8
  )

# select training and testing
# data based on this split
train <- rsample::training(ml_df_split) |>
  select(-is_flue_drought)
test <- rsample::testing(ml_df_split) |>
  select(-is_flue_drought)

#read in precompiled model
regression_model <- readRDS(
  here::here("vignettes/regression-models-LSO-GKF/regression_model_spatial_MODIS.rds")
)

# run the model on our test data
# using predict()
test_results <- predict(
  regression_model,
  test)$.pred

df <- data.frame(
  test,
  flue_predicted = test_results
)

## regression metrics
df|>
  yardstick::metrics(
    truth = flue,
    estimate = flue_predicted
  ) |>
  rename(
    metric = .metric,
    value  = .estimate
  ) |>
  select(
    metric,
    value
  ) |>
  mutate(
    value = round(value, 3)
  ) |>
  reactable::reactable()



```



```{r echo = FALSE, message=FALSE, warning=FALSE}
# read in training data
#readRDS to have the cluster variable for plotting clusters 
#na.omit to have same dataset on which the model was built 

set.seed(0)

ml_df1 <- readRDS(
  here::here("data/machine_learning_training_data_meteo.rds")
) |> 
 select (-date, -doy, -year) |>
  rename(
    NR_B1 = Nadir_Reflectance_Band1,
    NR_B2 = Nadir_Reflectance_Band2,
    NR_B3 = Nadir_Reflectance_Band3,
    NR_B4 = Nadir_Reflectance_Band4,
    NR_B5 = Nadir_Reflectance_Band5,
    NR_B6 = Nadir_Reflectance_Band6,
    NR_B7 = Nadir_Reflectance_Band7,
    LST = LST_Day_1km) |>
  rename(VPD_Day = VPD_DAY_F_MDS, TA_Day = TA_DAY_F_MDS) |>
   na.omit()

# create a data split across
# across both droughted and non-droughted days
ml_df_split1 <- ml_df1 |>
  rsample::initial_split(
    strata = is_flue_drought,
    prop = 0.8
  )

# select training and testing
# data based on this split
train1 <- rsample::training(ml_df_split1) |>
  select(-is_flue_drought)
test1 <- rsample::testing(ml_df_split1) |>
  select(-is_flue_drought)
# 
# #to make sure using same model 
# regresion_model <- best_model

# read in precompiled model
regression_model1 <- readRDS(
  here::here("vignettes/regression-models-LSO-GKF/regression_model_spatial_MODIS_Meteo.rds"))

# run the model on our test data
# using predict()
test_results1 <- predict(
  regression_model1,
  test1)$.pred

df1 <- data.frame(
  test1,
  flue_predicted = test_results1
)

## regression metrics
df1|>
  yardstick::metrics(
    truth = flue,
    estimate = flue_predicted
  ) |>
  rename(
    metric = .metric,
    value  = .estimate
  ) |>
  select(
    metric,
    value
  ) |>
  mutate(
    value = round(value, 3)
  ) |>
  reactable::reactable()

```


## Regression plots 

```{r echo = FALSE, message=FALSE, warning=FALSE, fig.align="center", fig.width=6, fig.height=7}
#| code-fold: true
#| label: regression-models 
#| fig-cap: "regression models (a) fLUE using MODIS bands (b) MODIS bands and meteo data."

# Calculate metrics
metrics_df <- df %>%
  yardstick::metrics(truth = flue, estimate = flue_predicted) %>%
  rename(metric = .metric, value = .estimate) %>%
  select(metric, value) %>%
  mutate(
    metric = case_when(
      metric == "rsq"  ~ "R²",   
      metric == "rmse" ~ "RMSE", 
      metric == "mae"  ~ "MAE",  
     #TRUE ~ metric              
    ),
    value = round(value, 3)
  )

# Calculate slope (regress predicted on observed)
slope <- lm(flue_predicted ~ flue, data = df)$coefficients[2] |> round(3)

# Add slope to metrics_df
metrics_df <- metrics_df %>%
  add_row(metric = "Slope", value = slope)

#remove mae
metrics_df <- metrics_df[-3, ]

# Create a string for the metrics to be used in the plot
metrics_text <- metrics_df %>%
  mutate(text = paste0(metric, ": ", value)) %>%
  pull(text) %>%
  paste(collapse = "\n")



# Define custom colors and shapes
custom_colors <- c("cGR" = "#E69F00", "cDD" = "darkorange4", "cLS" = "#999999", "cNA" = "darkcyan")
custom_shapes <- c("cGR" = 16, "cDD" = 17, "cLS" = 18,"cNA" = 19)

# Create the plot
p3 <-  ggplot(df, aes(x = flue, y = flue_predicted, color = cluster, shape = cluster)) +
  geom_point() +
  labs(x = "fLUE", y = "fLUE_predicted") +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  scale_color_manual(values = custom_colors) +
  scale_shape_manual(values = custom_shapes) +
  annotate("text", 
           x = min(df1$flue), 
           y = max(df1$flue_predicted), 
           label = metrics_text, 
           hjust = 0, 
           vjust = 0, 
           size = 3, 
           color = "black") +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white", colour = "black"),
    legend.text = element_text(size = 10),  
    legend.title = element_text(size = 12),
    axis.title = element_text(size = 14), 
    axis.text = element_text(size = 12),   
    # plot.title = element_text(size = 16, face = "bold"),
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.position = c(1, 0),
    legend.justification = c(1, 0)
  ) +
  coord_fixed(ratio = 1)

#regression model with TA and VPD included 

# Calculate metrics
metrics_df1 <- df1 %>%
  yardstick::metrics(truth = flue, estimate = flue_predicted) %>%
  rename(metric = .metric, value = .estimate) %>%
  select(metric, value) %>%
  mutate(
    metric = case_when(
      metric == "rsq"  ~ "R²",   
      metric == "rmse" ~ "RMSE", 
      metric == "mae"  ~ "MAE",  
      TRUE ~ metric         
    ),
    value = round(value, 3)
  )

# Calculate slope (regress predicted on observed)
slope <- lm(flue_predicted ~ flue, data = df1)$coefficients[2] |> round(3)

#remove mae 
metrics_df1 <- metrics_df1[-3, ]

# Add slope to metrics_df
metrics_df1 <- metrics_df1 %>%
  add_row(metric = "Slope", value = slope)

# Create a string for the metrics to be used in the plot
metrics_text1 <- metrics_df1 %>%
  mutate(text = paste0(metric, ": ", value)) %>%
  pull(text) %>%
  paste(collapse = "\n")

p4 <- ggplot(df1, aes(x = flue, y = flue_predicted, color = cluster, shape = cluster)) +
  geom_point() +
  labs(x = "fLUE", y = "fLUE_predicted") +
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) +
  scale_color_manual(values = custom_colors) +
  scale_shape_manual(values = custom_shapes) +
  annotate("text", 
           x = min(df1$flue), 
           y = max(df1$flue_predicted), 
           label = metrics_text1, 
           hjust = 0, 
           vjust = 0, 
           size = 3, 
           color = "black") +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white", colour = "black"), 
    legend.text = element_text(size = 10),  
    legend.title = element_text(size = 12),
    axis.title = element_text(size = 14), 
    axis.text = element_text(size = 12),   
    legend.background = element_blank(),
    legend.key = element_blank(),
    legend.position = c(1, 0),
    legend.justification = c(1, 0)
  ) +
  coord_fixed(ratio = 1)


#combined plot
Combined <- p3 + p4 + 
  plot_layout(ncol = 2) + 
  plot_annotation(
    tag_levels = "a",
    tag_prefix = "(",
    tag_suffix = ")"
    )

Combined 
ggsave("manuscript/Version1/fig1_Cor1.png", plot = Combined, width = 10, height = 5, dpi =700)

```
